### ISSUE TITLE
About Autolayout issues with this lib

### ISSUE THREAD

**Issue by VMTrinh** [antiguab/BATabBarController#10]
My autolayout not working when add into BATabBarController.
How to fix it?

**Comment by antiguab** [comment]
@VMTrinh  - Can you post a sample project? I haven't had any auto-layout issues.

**Comment by pmehul55** [comment]
Hello
I am facing one layout issue when Toggle In-Call Status Bar option ON

Please check attached screenshots.

![screen shot 2017-09-29 at 3 46 24 pm](https://user-images.githubusercontent.com/7946609/31012023-f65b5560-a52d-11e7-9996-ced03eec64f6.png)
![simulator screen shot 29-sep-2017 1 55 30 pm](https://user-images.githubusercontent.com/7946609/31012032-faef2e62-a52d-11e7-9483-58cd439f4457.png)
![simulator screen shot 29-sep-2017 1 55 43 pm](https://user-images.githubusercontent.com/7946609/31012033-fb2aa4c4-a52d-11e7-9ce9-cf1e5f2196ec.png)

**Comment by antiguab** [comment]
@pmehul55 - I've tried toggle the in-call status bar in several scenarios and it still didn't get cut off. Can you provide specific steps?

**Comment by pmehul55** [comment]
@antiguab - 
Step 1 : Launch app in your device / Simulator.

Step 2 :  Now put app into background mode and click on "Toggle In-Call Status Bar" option into simulator or share hotspot from your real device.

Step 3 : Now come into foreground mode here i think this issue can reproducible.

**Comment by antiguab** [comment]
You're right - I'll look into this

**Comment by antiguab** [comment]
Looked into and it looks like a lot of custom views suffer from resizing with the in call status bar. I'm not seeing a general or clean solution, but there are solutions for resizing the entire view as a whole you can implement:

https://stackoverflow.com/questions/43595514/uiviewcontroller-in-call-status-bar-issue
https://stackoverflow.com/questions/25882609/how-to-do-layout-to-handle-in-call-double-height-status-bar-for-custom-present
