### ISSUE TITLE
xcode8 or ios10 bug??

### ISSUE THREAD

**Issue by amjunliang** [antiguab/BATabBarController#14]
Thanks to open source, I use it in the project to achieve the very good-looking animation, but recently the package out of the question, when the xcode 8.2, when the scheme is set to release, all is lost, but set the debug mode, the performance is normal. You can repeat this disaster, I hope you can check it, I also check tomorrow
![screenshot](https://cloud.githubusercontent.com/assets/19588302/20348619/559a1fb6-ac41-11e6-8e28-b076ba15de01.png)

**Comment by antiguab** [comment]
@amjunliang - Strange I haven't experienced this. I'll do a little research and let you know.

**Comment by CalvinTp** [comment]
I just loaded the code and found the same issue. When the scheme is set to released, the animation is lost. Has this issue been solved?

**Comment by antiguab** [comment]
@CalvinTp super weird - I've started looking into it again but still haven't figured out why the animation layer specifically choses to disappear. Do you get the same result as above? For me only the line layers are missing

**Comment by CalvinTp** [comment]
Sorry for the delay in responding to you, yea only the line layers are missing.

**Comment by antiguab** [comment]
@CalvinTp - this should be resolved in v0.1.5 !
