### ISSUE TITLE
Update badge value

### ISSUE THREAD

**Issue by palmitoto** [antiguab/BATabBarController#20]
Hi,

i can't update badge value. I missed something ?
This is how I try to update the badge:

`            [[[tabBarController.tabBarItems objectAtIndex:2]badge]setBadgeValue:@8];
`

Thank you for your help !

**Comment by palmitoto** [comment]
Any idea ? :-(

**Comment by antiguab** [comment]
Sorry for the late response. Do you have a sample app I can take a look at? I'll have to double-check how much of the badge API has been implemented

**Comment by antiguab** [comment]
?

**Comment by palmitoto** [comment]
Hello, Sorry for the delay...
I went back on native UITabBar, I encountered too much difficulty  compared to the added value of your project.

Sincerely

**Comment by antiguab** [comment]
ah no worries - sorry it wasn't a good fit!
