### ISSUE TITLE
iOS11 for iPhonex

### ISSUE THREAD

**Issue by kb100824** [antiguab/BATabBarController#24]
Tabbar iOS11 for iPhonex
![image](https://user-images.githubusercontent.com/8489350/30725573-3ff4e922-9f78-11e7-9636-828bca6dbc3d.png)

**Comment by antiguab** [comment]
ah wow - I'll have to look into this

**Comment by kb100824** [comment]
tks ！I am also trying to modify your source code @antiguab

**Comment by antiguab** [comment]
Should be resolve in v0.1.5 !

**Comment by pmehul55** [comment]
Inside 
BATabBar.m >> - (void)updateConstraints  Method

if (@available(iOS 11.0, *)) {
            make.bottom.equalTo(self.superview.mas_bottomMargin);
        } else {
            // Fallback on earlier versions
            make.bottom.equalTo(self.superview.mas_bottom);
        }

it will fix problem for iPhone X
