### ISSUE TITLE
How to select tab item programmatically ?

### ISSUE THREAD

**Issue by risingworld777** [antiguab/BATabBarController#25]
Thanks for your great open source.

I tried to use this method to select other tab programmatically. 

`[self.vc.tabBar selectedTabItem:1 animated:YES];`

It works. But the selected image of previous tab still  remains.

**Comment by antiguab** [comment]
this should be fixed in 0.1.5. Also similar `UITabBarController`, the best way to programmatically switch tabs is using:
```
[self.vc setSelectedViewController:viewControllerAtIndex1 animated:YES];
```
