### ISSUE TITLE
Tabbar icons pixelated 

### ISSUE THREAD

**Issue by Nextweb1** [antiguab/BATabBarController#34]
I'm using BATabBarController(Cocoa pod), everything works fine, but the tab icons are pixelated, tried variant size of icons still icons are pixelated especially in 5s,6,7&8, attached screenshots

![img_5193](https://user-images.githubusercontent.com/22512762/39572635-9aed9dc2-4eed-11e8-89a7-5e848acd3ee5.png)

**Comment by antiguab** [comment]
Could that be due to the image resolution and not having properly 2x and 3x icons?
