### ISSUE TITLE
Tab Bar animation not working after in development build

### ISSUE THREAD

**Issue by rajamohan0s** [antiguab/BATabBarController#36]
The animation of tab bar is working with running the app via xcode. But, It's not working installing app from App store or Directly installing development build.

Anyone did faced this issue? How can I solve it?

**Comment by Meet1313** [comment]
Have you find any solution? I have same issue.

**Comment by rajamohan0s** [comment]
@Meet1313 , Nope I tried but I cant, It may be because of deprecated API's.

**Comment by Meet1313** [comment]
From Simulator its working fine but from testFlight it is not working

**Comment by antiguab** [comment]
Is this still occurring. I haven't been able to reproduce it.

**Comment by rajamohan0s** [comment]
Yes, still there. Not working when installing app from Xcode or test flight to device. But works fine in debugging both device or simulator.

**Comment by antiguab** [comment]
I see what it was. I was able to recreate the issue with a release build. There were some property attributes that were incorrect. This should be resolved in the latest objc version (0.1.6). Can you give it a try and let me know if the issue persists?
