### ISSUE TITLE
Vertical tabbar

### ISSUE THREAD

**Issue by tbaranes** [antiguab/BATabBarController#4]
Not sure if we can still call it a TabBar, but it would be awesome to have this feature. It could be useful for universal application:
- Classic TabBar at the bottom on iPhone
- Vertical TabBar (like a permanent menu) on iPad

The most of animated tabbar libraries are based on `UITabBar` which make that feature impossible, but for `BATabBarController` it looks possible since it's based on `UIView`... :)

**Comment by antiguab** [comment]
This is an awesome idea!! I'll definitely look into it 👍 👍
