### ISSUE TITLE
iOS 8.0 support

### ISSUE THREAD

**Issue by tbaranes** [antiguab/BATabBarController#5]
Currently, `BATabBarController` is targeting only iOS8.1+, is there any reason to not support iOS8.0?

**Comment by antiguab** [comment]
I couldn't download a simulator for it :( - Xcode 7.3 seems to only be able to go back as far as 8.1. I don't think there is any issues on iOS 8.0, but I was never able to test it

**Comment by tbaranes** [comment]
Just check in case, but I can't get it anymore too... I think a solution could support it anyway. If there is an issue, you will have quickly some feedbacks, and we could fix it somehow. You may also let a note in the README to say that you didn't test it on iOS 8.0 but should work as expected.

Targeting iOS8.1 is a bit annoying since generally we target iOS8.0 or 9.0 :(

**Comment by antiguab** [comment]
got a hold of an old device for a bit and testing with iOS8.0 - as expected, no issues :). version 0.1.2 should support it now!
