### ISSUE TITLE
Circle is too big on first load

### ISSUE THREAD

**Issue by scourgy** [antiguab/BATabBarController#56]
Hi mate, see what happens when I present my BaTabBarController - the circle of the selected item is too big:

![IMG_3764](https://user-images.githubusercontent.com/7067535/72679428-afbc4980-3ab7-11ea-84a5-411bce2c63dd.PNG)

Device is iPhone X (iOS 13.1.2)

**Comment by antiguab** [comment]
Hey - can you give me more info on what device you're trying this on? Sample code?

**Comment by antiguab** [comment]
Closed due to inactivity
