### ISSUE TITLE
tab bar icon image size

### ISSUE THREAD

**Issue by smn-khan** [antiguab/BATabBarController#8]
image showing very small ..

https://www.dropbox.com/s/415v0uab4w0a8xf/Screenshot%202016-09-29%2001.28.49.png?dl=0

**Comment by ykl7** [comment]
@smn-khan just to confirm, the image in dropbox  is the undesired size tab bar, right?

**Comment by antiguab** [comment]
@smn-khan - can you send me those pictures so I can try it out? You may need to use higher resolution images
